# Generated by Django 5.1 on 2025-05-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='room_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='uid',
            field=models.CharField(max_length=200),
        ),
    ]
