# Generated by Django 5.1 on 2025-05-16 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_roommember_name_alter_roommember_room_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommember',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
