# Generated by Django 5.1 on 2025-05-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_roommember_joined_at_roommember_left_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommember',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='roommember',
            name='left_at',
        ),
    ]
