# Generated by Django 5.1 on 2025-05-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_roommember_joined_at_roommember_left_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
